<?xml version="1.0" encoding="utf-8"?><Database Name="epg" Class="UsersDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=172.18.163.2;Initial Catalog=epg;Persist Security Info=True;User ID=sa" SettingsObjectName="WxEpg.DataPush.Properties.Settings" SettingsPropertyName="epgConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.users" Member="users">
    <Type Name="users">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userid" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="wxid" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="head" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="companyid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="lasttime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="subscribe" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="province" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="city" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(11)" CanBeNull="true" />
    </Type>
  </Table>
</Database>