#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WxEpg.Statistic.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="epg")]
	public partial class DataJobListViewDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public DataJobListViewDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["epgConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataJobListViewDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataJobListViewDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataJobListViewDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataJobListViewDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<JobListView> JobListView
		{
			get
			{
				return this.GetTable<JobListView>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.JobListView")]
	public partial class JobListView
	{
		
		private System.Nullable<int> _id;
		
		private System.Nullable<int> _channelid;
		
		private System.Nullable<System.DateTime> _playtime;
		
		private System.Nullable<int> _duration;
		
		private string _eventname;
		
		private System.Nullable<int> _programid;
		
		private string _mainType;
		
		private string _imgs;
		
		private string _category;
		
		private string _channelname;
		
		private string _viagroup;
		
		private System.Nullable<decimal> _weightIndex;
		
		public JobListView()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_channelid", DbType="Int")]
		public System.Nullable<int> channelid
		{
			get
			{
				return this._channelid;
			}
			set
			{
				if ((this._channelid != value))
				{
					this._channelid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playtime", DbType="DateTime")]
		public System.Nullable<System.DateTime> playtime
		{
			get
			{
				return this._playtime;
			}
			set
			{
				if ((this._playtime != value))
				{
					this._playtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="Int")]
		public System.Nullable<int> duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this._duration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventname", DbType="VarChar(150)")]
		public string eventname
		{
			get
			{
				return this._eventname;
			}
			set
			{
				if ((this._eventname != value))
				{
					this._eventname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programid", DbType="Int")]
		public System.Nullable<int> programid
		{
			get
			{
				return this._programid;
			}
			set
			{
				if ((this._programid != value))
				{
					this._programid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mainType", DbType="VarChar(50)")]
		public string mainType
		{
			get
			{
				return this._mainType;
			}
			set
			{
				if ((this._mainType != value))
				{
					this._mainType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgs", DbType="VarChar(500)")]
		public string imgs
		{
			get
			{
				return this._imgs;
			}
			set
			{
				if ((this._imgs != value))
				{
					this._imgs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="VarChar(50)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this._category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_channelname", DbType="VarChar(50)")]
		public string channelname
		{
			get
			{
				return this._channelname;
			}
			set
			{
				if ((this._channelname != value))
				{
					this._channelname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viagroup", DbType="VarChar(150)")]
		public string viagroup
		{
			get
			{
				return this._viagroup;
			}
			set
			{
				if ((this._viagroup != value))
				{
					this._viagroup = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_weightIndex", DbType="Decimal(7,3)")]
		public System.Nullable<decimal> weightIndex
		{
			get
			{
				return this._weightIndex;
			}
			set
			{
				if ((this._weightIndex != value))
				{
					this._weightIndex = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
