<?xml version="1.0" encoding="utf-8"?><Database Name="epg" Class="DataTaskStatusDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=172.18.163.2;Initial Catalog=epg;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="epgConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TaskStatus" Member="TaskStatus">
    <Type Name="TaskStatus">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VideoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TaskType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EditId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EditTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AuditId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AuditTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Step" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>