#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WxEpg.Mobile.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="epg")]
	public partial class DataMobileEventDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public DataMobileEventDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["epgConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataMobileEventDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMobileEventDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMobileEventDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataMobileEventDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MobileEvent> MobileEvent
		{
			get
			{
				return this.GetTable<MobileEvent>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_queryevent")]
		public ISingleResult<sp_queryeventResult> sp_queryevent([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name);
			return ((ISingleResult<sp_queryeventResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_getplays")]
		public ISingleResult<sp_getplaysResult> sp_getplays([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> companyId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string playTime, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cid, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> count)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), companyId, playTime, category, cid, count);
			return ((ISingleResult<sp_getplaysResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MobileEvent")]
	public partial class MobileEvent
	{
		
		private int _id;
		
		private int _channelid;
		
		private System.DateTime _playtime;
		
		private int _duration;
		
		private string _eventname;
		
		private System.Nullable<int> _programid;
		
		public MobileEvent()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_channelid", DbType="Int NOT NULL")]
		public int channelid
		{
			get
			{
				return this._channelid;
			}
			set
			{
				if ((this._channelid != value))
				{
					this._channelid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playtime", DbType="DateTime NOT NULL")]
		public System.DateTime playtime
		{
			get
			{
				return this._playtime;
			}
			set
			{
				if ((this._playtime != value))
				{
					this._playtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="Int NOT NULL")]
		public int duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this._duration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventname", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string eventname
		{
			get
			{
				return this._eventname;
			}
			set
			{
				if ((this._eventname != value))
				{
					this._eventname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programid", DbType="Int")]
		public System.Nullable<int> programid
		{
			get
			{
				return this._programid;
			}
			set
			{
				if ((this._programid != value))
				{
					this._programid = value;
				}
			}
		}
	}
	
	public partial class sp_queryeventResult
	{
		
		private System.Nullable<int> _VideoId;
		
		private string _Name;
		
		private string _MainType;
		
		public sp_queryeventResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoId", DbType="Int")]
		public System.Nullable<int> VideoId
		{
			get
			{
				return this._VideoId;
			}
			set
			{
				if ((this._VideoId != value))
				{
					this._VideoId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(150)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MainType", DbType="VarChar(50)")]
		public string MainType
		{
			get
			{
				return this._MainType;
			}
			set
			{
				if ((this._MainType != value))
				{
					this._MainType = value;
				}
			}
		}
	}
	
	public partial class sp_getplaysResult
	{
		
		private int _channelid;
		
		private System.DateTime _playtime;
		
		private string _eventname;
		
		private int _duration;
		
		private System.Nullable<int> _programid;
		
		private string _mainType;
		
		private string _category;
		
		private System.Nullable<int> _hasplay;
		
		private string _channelName;
		
		private System.Nullable<int> _LoveCount;
		
		private System.Nullable<int> _CommentCount;
		
		private System.Nullable<decimal> _Weight;
		
		public sp_getplaysResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_channelid", DbType="Int NOT NULL")]
		public int channelid
		{
			get
			{
				return this._channelid;
			}
			set
			{
				if ((this._channelid != value))
				{
					this._channelid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_playtime", DbType="DateTime NOT NULL")]
		public System.DateTime playtime
		{
			get
			{
				return this._playtime;
			}
			set
			{
				if ((this._playtime != value))
				{
					this._playtime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eventname", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string eventname
		{
			get
			{
				return this._eventname;
			}
			set
			{
				if ((this._eventname != value))
				{
					this._eventname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="Int NOT NULL")]
		public int duration
		{
			get
			{
				return this._duration;
			}
			set
			{
				if ((this._duration != value))
				{
					this._duration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_programid", DbType="Int")]
		public System.Nullable<int> programid
		{
			get
			{
				return this._programid;
			}
			set
			{
				if ((this._programid != value))
				{
					this._programid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mainType", DbType="VarChar(50)")]
		public string mainType
		{
			get
			{
				return this._mainType;
			}
			set
			{
				if ((this._mainType != value))
				{
					this._mainType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="VarChar(50)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this._category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hasplay", DbType="Int")]
		public System.Nullable<int> hasplay
		{
			get
			{
				return this._hasplay;
			}
			set
			{
				if ((this._hasplay != value))
				{
					this._hasplay = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_channelName", DbType="VarChar(50)")]
		public string channelName
		{
			get
			{
				return this._channelName;
			}
			set
			{
				if ((this._channelName != value))
				{
					this._channelName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoveCount", DbType="Int")]
		public System.Nullable<int> LoveCount
		{
			get
			{
				return this._LoveCount;
			}
			set
			{
				if ((this._LoveCount != value))
				{
					this._LoveCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CommentCount", DbType="Int")]
		public System.Nullable<int> CommentCount
		{
			get
			{
				return this._CommentCount;
			}
			set
			{
				if ((this._CommentCount != value))
				{
					this._CommentCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Weight", DbType="Decimal(7,1)")]
		public System.Nullable<decimal> Weight
		{
			get
			{
				return this._Weight;
			}
			set
			{
				if ((this._Weight != value))
				{
					this._Weight = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
