<?xml version="1.0" encoding="utf-8"?><Database Name="epg" Class="DataArticleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=172.18.163.2;Initial Catalog=epg;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="epgConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Article" Member="Article">
    <Type Name="Article">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VideoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Uri" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Summary" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="PublicName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PubTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UpdateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsUpdate" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>